function test
    ctx = makecontext(600, 600);
    tic
        ctx = render(...
            ctx, ...
            [
                struct('v_position', [0.0; 1.0; 0.0; 1.0], 'color', [1.0, 0.0, 0.0])
                struct('v_position', [-1.0; -1.0; 0.0; 1.0], 'color', [0.0, 1.0, 0.0])
                struct('v_position', [1.0; -1.0; 0.0; 1.0], 'color', [0.0, 0.0, 1.0])
            ], ...
            @(v, u) v, ...
            @(v, u) v.color, ...
            [], ...
            @(w1, w2, w3, v1, v2, v3) struct('color', w1 * v1.color + w2 * v2.color + w3 * v3.color) ...
        );
    toc

    imshow(ctx.buffer);
